FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

COPY program.cs .

RUN dotnet new console -o myapp

RUN mv program.cs myapp/Program.cs

WORKDIR /app/myapp

RUN dotnet build

CMD ["dotnet", "bin/Debug/net8.0/myapp.dll"]
